### ISSUE TITLE
Worker thread failure from: data_qld/validation.py, in process_schema_fields 

### ISSUE THREAD

**Issue by duttonw** [qld-gov-au/ckanext-data-qld#190]
data_qld/validation.py, in process_schema_fields is not verifying that its on web thread or background worker thread.

since tk.request.files does not exist on worker thread.

File "/srv/app/src/ckanext-data-qld/ckanext/data_qld/validation.py", line 78, in read_schema_from_request
    form_data = tk.request.files
```
2023-03-06 06:19:27,009 DEBUG [ckanext.validation.jobs] Validating resource: f6ac0fd9-84dd-4d98-b146-cc53ac3d23b5
2023-03-06 06:19:27,010 DEBUG [ckanext.validation.validation_status_helper] updateValidationJobStatus: f6ac0fd9-84dd-4d98-b146-cc53ac3d23b5 status: running
2023-03-06 06:19:27,015 DEBUG [ckanext.validation.validation_status_helper] getValidationJob: f6ac0fd9-84dd-4d98-b146-cc53ac3d23b5
2023-03-06 06:19:27,058 DEBUG [ckanext.harvest.model] Harvest tables already exist
2023-03-06 06:19:27,073 DEBUG [ckanext.harvest.model] Harvest tables already exist
2023-03-06 06:19:27,077 WARNI [ckanext.csrf_filter.anti_csrf] Site ParseResult(scheme='http', netloc='ckan:5000', path='', params='', query='', fragment='') is not secure! CSRF tokens may be exposed!
2023-03-06 06:19:27,077 INFO  [ckanext.csrf_filter.anti_csrf] Obtained secret key from beaker.session.secret
2023-03-06 06:19:27,078 DEBUG [ckanext.resource_type_validation.resource_type_validation] Allowed file extensions: ['accdb', 'asc', 'cdf', 'csv', 'doc', 'docx', 'ecw', 'esri', 'fgdb', 'gdb', 'geojson', 'geotiff', 'gpkg', 'gpx', 'html', 'jp2', 'jpeg', 'jpg', 'json', 'kml', 'kmz', 'mdb', 'mtl', 'n3', 'nc', 'obj', 'parquet', 'pdf', 'png', 'ppt', 'pqt', 'pptx', 'rdf', 'rtf', 'shp', 'sparql', 'tab', 'tif', 'tiff', 'topojson', 'tsv', 'ttf', 'txt', 'wfs', 'wmts', 'xls', 'xlsx', 'xml', 'zip']
2023-03-06 06:19:27,106 WARNI [ckanext.csrf_filter.anti_csrf] Site ParseResult(scheme='http', netloc='ckan:5000', path='', params='', query='', fragment='') is not secure! CSRF tokens may be exposed!
2023-03-06 06:19:27,106 INFO  [ckanext.csrf_filter.anti_csrf] Obtained secret key from beaker.session.secret
2023-03-06 06:19:27,107 DEBUG [ckanext.resource_type_validation.resource_type_validation] Allowed file extensions: ['accdb', 'asc', 'cdf', 'csv', 'doc', 'docx', 'ecw', 'esri', 'fgdb', 'gdb', 'geojson', 'geotiff', 'gpkg', 'gpx', 'html', 'jp2', 'jpeg', 'jpg', 'json', 'kml', 'kmz', 'mdb', 'mtl', 'n3', 'nc', 'obj', 'parquet', 'pdf', 'png', 'ppt', 'pqt', 'pptx', 'rdf', 'rtf', 'shp', 'sparql', 'tab', 'tif', 'tiff', 'topojson', 'tsv', 'ttf', 'txt', 'wfs', 'wmts', 'xls', 'xlsx', 'xml', 'zip']
2023-03-06 06:19:27,322 DEBUG [ckanext.validation.jobs] Validating source: /var/lib/ckan/resources/f6a/c0f/d9-84dd-4d98-b146-cc53ac3d23b5
2023-03-06 06:19:27,323 DEBUG [ckanext.validation.validation_status_helper] updateValidationJobStatus: f6ac0fd9-84dd-4d98-b146-cc53ac3d23b5 status: success
2023-03-06 06:19:27,361 INFO  [ckanext.qa.tasks] Openness scoring package random_package (1 resources)
2023-03-06 06:19:27,367 INFO  [ckanext.qa.sniff_format] Sniffing file format of: /var/lib/ckan/resources/f6a/c0f/d9-84dd-4d98-b146-cc53ac3d23b5
2023-03-06 06:19:27,368 INFO  [ckanext.qa.sniff_format] Magic detects file as: application/csv
2023-03-06 06:19:27,377 INFO  [ckanext.qa.sniff_format] Is CSV because 2.0 cells per row (22 cells, 11 rows)
2023-03-06 06:19:27,381 DEBUG [ckanext.resource_type_validation.resource_type_validation] f6ac0fd9-84dd-4d98-b146-cc53ac3d23b5 is not an uploaded resource, skipping validation
2023-03-06 06:19:27,381 INFO  [ckanext.qa.sniff_format] Mimetype translates to filetype: CSV
2023-03-06 06:19:27,385 INFO  [ckanext.qa.tasks] Score: 3 Reason: Content of file appeared to be format "CSV" which receives openness score: 3.
2023-03-06 06:19:27,386 INFO  [ckanext.qa.tasks] Openness scoring: 
{'openness_score': 3, 'openness_score_reason': 'Content of file appeared to be format "CSV" which receives openness score: 3.', 'format': 'CSV', 'archival_timestamp': '2023-03-06T06:19:25.904667'}
<Resource id=f6ac0fd9-84dd-4d98-b146-cc53ac3d23b5 package_id=0d6e776c-fcbe-408d-8744-fbe24fb92932 url=test.csv format=csv description=Former world name consumer laugh street debate let. hash= position=0 name=invisible-resource resource_type=None mimetype=application/csv mimetype_inner=None size=7884 created=2023-03-06 06:19:25.275977 last_modified=2023-03-06 06:19:25.483859 metadata_modified=2023-03-06 06:19:25.486172 cache_url=None cache_last_updated=None url_type=upload extras={'_xloader': False, 'align_default_schema': False, 'datastore_active': False, 'datastore_contains_all_records_of_source_file': False, 'governance_acknowledgement': 'NO', 'privacy_assessment_result': 'Nor career particularly reason nearly project small dinner.', 'resource_visible': 'FALSE', 'schema': '{"fields": [{"format": "default", "name": "Game Number", "type": "integer"}, {"format": "default", "name": "Game Length", "type": "integer"}], "missingValues": ["Resource schema"]}'} state=active>
'test.csv'


2023-03-06 06:19:27,402 INFO  [ckanext.qa.tasks] QA results updated ok
2023-03-06 06:19:27,402 INFO  [ckanext.qa.tasks] CKAN updated with openness score
2023-03-06 06:19:27,429 ERROR [ckan.lib.jobs] Job 849078b5-490c-4d61-9848-a8f8790db8ff on worker rq:worker:c773b50aa48b48558fe5c6de33db17e1 raised an exception: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/usr/lib/python3.8/site-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/usr/lib/python3.8/site-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/srv/app/src/ckanext-validation/ckanext/validation/jobs.py", line 104, in run_validation_job
    t.get_action('resource_patch')(
  File "/srv/app/src/ckan/ckan/logic/__init__.py", line 504, in wrapped
    result = _action(context, data_dict, **kw)
  File "/srv/app/src/ckan/ckan/logic/action/patch.py", line 81, in resource_patch
    return _update.resource_update(context, patched)
  File "/srv/app/src/ckan/ckan/logic/action/update.py", line 107, in resource_update
    updated_pkg_dict = _get_action('package_update')(context, pkg_dict)
  File "/srv/app/src/ckan/ckan/logic/__init__.py", line 504, in wrapped
    result = _action(context, data_dict, **kw)
  File "/srv/app/src/ckan/ckan/logic/action/update.py", line 301, in package_update
    data, errors = lib_plugins.plugin_validate(
  File "/srv/app/src/ckan/ckan/lib/plugins.py", line 302, in plugin_validate
    result = plugin.validate(context, data_dict, schema, action)
  File "/srv/app/src/ckanext-scheming/ckanext/scheming/plugins.py", line 308, in validate
    return navl_validate(data_dict, schema, context)
  File "/srv/app/src/ckan/ckan/lib/navl/dictization_functions.py", line 285, in validate
    converted_data, errors = _validate(flattened, schema, validators_context)
  File "/srv/app/src/ckan/ckan/lib/navl/dictization_functions.py", line 335, in _validate
    convert(converter, key, converted_data, errors, context)
  File "/srv/app/src/ckan/ckan/lib/navl/dictization_functions.py", line 237, in convert
    converter(key, converted_data, errors, context)
  File "/srv/app/src/ckanext-data-qld/ckanext/data_qld/validation.py", line 49, in process_schema_fields
    schema_from_upload_request = read_schema_from_request()
  File "/srv/app/src/ckanext-data-qld/ckanext/data_qld/validation.py", line 78, in read_schema_from_request
    form_data = tk.request.files
  File "/usr/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/lib/python3.8/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/usr/lib/python3.8/site-packages/flask/globals.py", line 38, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
RuntimeError: Working outside of request context.
```

**Comment by duttonw** [comment]
fixed by https://github.com/qld-gov-au/ckanext-data-qld/commit/c3e49490afdedb88034ed34332e4ddd6c92cd49f
